/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TodoComponent {
        "action": () => void;
        /**
          * Todoo list
         */
        "todos": Array<Object>;
    }
    interface TodoItem {
        "desc": string;
        "done"?: boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTodoComponentElement extends Components.TodoComponent, HTMLStencilElement {
    }
    var HTMLTodoComponentElement: {
        prototype: HTMLTodoComponentElement;
        new (): HTMLTodoComponentElement;
    };
    interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {
    }
    var HTMLTodoItemElement: {
        prototype: HTMLTodoItemElement;
        new (): HTMLTodoItemElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "todo-component": HTMLTodoComponentElement;
        "todo-item": HTMLTodoItemElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TodoComponent {
        "action"?: () => void;
        /**
          * Todoo list
         */
        "todos"?: Array<Object>;
    }
    interface TodoItem {
        "desc"?: string;
        "done"?: boolean;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "todo-component": TodoComponent;
        "todo-item": TodoItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "todo-component": LocalJSX.TodoComponent & JSXBase.HTMLAttributes<HTMLTodoComponentElement>;
            "todo-item": LocalJSX.TodoItem & JSXBase.HTMLAttributes<HTMLTodoItemElement>;
        }
    }
}
